PuZheng/cloud-dashing/cloud_dashing/models.py
# -*- coding: UTF-8 -*-
from datetime import datetime

from flask.ext.babel import _
from .database import db


class User(db.Model):

    __tablename__ = 'TB_USER'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, nullable=False)
    password = db.Column(db.String(128), doc=u'保存为明文密码的sha256值')
    group_id = db.Column(db.Integer, db.ForeignKey('TB_GROUP.id'),
                         nullable=False)
    group = db.relationship('Group')
    create_time = db.Column(db.DateTime, default=datetime.now)
    enabled = db.Column(db.Boolean, default=False)

    def __unicode__(self):
        return self.name


class Group(db.Model):

    __tablename__ = 'TB_GROUP'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(16), unique=True)
    default_url = db.Column(db.String(256))

    def __unicode__(self):
        return _(self.name)

    def __repr__(self):
        return '<Group: %s>' % self.name

PuZheng/cloud-dashing/cloud_dashing/apis/__init__.py
# -*- coding: UTF-8 -*-
import types
from path import path
from .model_wrapper import ModelWrapper, wraps, unwraps

# install all the wrappers in this module
for fname in path(__path__[0]).files("[!_]*.py"):
    fname = fname.basename()[:-len(".py")]
    package = __import__(str("cloud_dashing.apis." + fname),
                         fromlist=[str(fname)])
    for k, v in package.__dict__.items():
        if isinstance(v, types.TypeType) and \
                issubclass(v, ModelWrapper) and \
                k.endswith("Wrapper"):
            globals()[k] = v

PuZheng/cloud-dashing/cloud_dashing/portal/user/__init__.py
# -*- coding: UTF-8 -*-
from flask import Blueprint


user_ws = Blueprint("user-ws", __name__, static_folder="static",
                    template_folder="templates")

user = Blueprint("user", __name__, static_folder="static",
                 template_folder="templates")

from . import views

PuZheng/cloud-dashing/cloud_dashing/portal/user/views.py
# -*- coding: UTF-8 -*-
from flask import (jsonify, request, render_template, redirect, session,
                   current_app)
from flask.ext.wtf import Form
from flask.ext.babel import _
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired
from werkzeug.security import generate_password_hash
from flask.ext.login import (current_user, login_user, login_required,
                             logout_user)
from flask.ext.principal import Identity, AnonymousIdentity, identity_changed

from cloud_dashing.portal.user import user_ws, user
from cloud_dashing.models import User, Group
from cloud_dashing import utils, apis
from cloud_dashing.exceptions import AuthenticateFailure


@user_ws.route('/register', methods=['POST'])
def register_ws():
    name = request.args.get("name", type=str)
    password = request.args.get("password", type=str)
    if not name or not password:
        return u"需要name或者password字段", 403

    user = User.query.filter(User.name == name).first()
    if user:
        return u'用户名已存在, 请更换注册名', 403
    user = utils.do_commit(User(name=name,
                                password=generate_password_hash(
                                    password, 'pbkdf2:sha256'),
                                group=Group.query.get(const.CUSTOMER_GROUP)))
    user = apis.wraps(user)
    return jsonify(user.as_dict(include_auth_token=True)), 201


@user_ws.route("/login", methods=["POST"])
def login_ws():
    name = request.args.get("name", type=str)
    password = request.args.get("password", type=str)
    if not name or not password:
        return u"需要name或者password字段", 403
    try:
        user = apis.user.authenticate(name, password)
    except AuthenticateFailure:
        return u'用户名或者密码错误', 403
    return jsonify(user.as_dict(include_auth_token=True))


class LoginForm(Form):

    username = TextField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == "GET":
        if current_user.is_anonymous():
            return render_template("user/login.html", form=form,
                                   error=request.args.get('error'),
                                   next_url=request.args.get('next'))
        return redirect("/")
    else:
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            try:
                user = apis.user.authenticate(username, password)
            except AuthenticateFailure:
                return render_template("user/login.html",
                                       error=_("invalid username or password"),
                                       form=form), 403
            if not login_user(user):
                return render_template("user/login.html",
                                       error=_("failed to login")), 403

            identity_changed.send(current_app._get_current_object(),
                                  identity=Identity(user.id))
            return redirect(request.args.get('next') or "/")
        return render_template("user/login.html",
                               error=_("please input username or password"),
                               form=form), 403


@user.route("/logout")
@login_required
def logout():
    try:
        logout_user()
    except Exception:  # in case sesson expire
        pass
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())
    next_url = request.args.get("next", "/")
    return redirect(next_url)

PuZheng/cloud-dashing/cloud_dashing/templates/cloud-dashing.html
{% extends "layout.html" %}
{% block head_block %}
  {{ super() }}
  <!--[if lte IE 8]>
    <script type="text/javascript" src="{{ url_for('static', filename='components/flot/excanvas.min.js') }}"></script>
    <![endif]-->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}"/>
  <link rel="stylesheet" href="{{ url_for('static', filename='components/backgrid/lib/backgrid.min.css') }}"/>
{% endblock %}
{% block main %}
  <div class="container">

    <div id="main">
      <div class="row">
        <div name="display">
          <ul class="view-switcher nav nav-pills nav-stacked pull-left">
            <li class="map-li"><a href="#map">地图</a></li>
            <li class="table-li"><a href="#table">列表</a></li>
            <li class="stat-li"><a href="#stat">统计</a></li>
          </ul>
          <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
            <div class="map"></div>
            <div class="table"></div>
            <div class="stat"></div>
            <div class="timeline"></div>
            <div class="stable"></div>
          </div>
        </div>
        <div class="control-panel col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>
      </div>
    </div>
  </div><!-- /.container -->
{% endblock %}

{% block tail_block %}
  {{ super() }}
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=SwpHSZo7lxB794VNXA9U2d5q"></script>
  <script type="text/javascript" data-main="{{ url_for('static', filename='js/main.js', bust=time) }}" src="{{ url_for('static', filename='components/requirejs/require.js') }}"></script>

{% endblock %}

PuZheng/cloud-dashing/cloud_dashing/templates/error.html
{% extends "layout.html" %}
{% block page_title %}
  公有云监控 - {{ _('Error') }}
{% endblock %}
{% block main %}
  <div class="container">
    <div>
      <h3 class="alert alert-danger">
        {{ error }}
      </h3>
      {% if detail %}
        {{ detail|safe }}
      {% endif %}
    </div>
    <a href="{{ back_url }}" class="btn btn-primary btn-default">{{ _('Back') }}</a>
  </div>
{% endblock %}

PuZheng/cloud-dashing/cloud_dashing/templates/index.html
{% extends "layout.html" %}
{% block head_block %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <script src="{{ url_for('static', filename='components/jquery/jquery.min.js') }}"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script>
    $(function () {
      $("#modal").on("show.bs.modal", function () {
        $("#copy-input").val($("<iframe></iframe>").attr("src", location.origin + $("iframe").attr("src"))[0].outerHTML);
      });
    });
  </script>
{% endblock %}

{% block main %}
  <button id="embed-link" class="btn btn-default pull-right" data-toggle="modal" data-target="#modal" type="button">
    嵌入
  </button>
  <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">复制</h4>
        </div>
        <div class="modal-body">
          <p>将下面内容复制到您的网页中</p>

            <input type="text" class="form-control" id="copy-input"/>
          </div>
        </div>
      </div>
    </div>

  </div>

  <iframe id="main" src="/cloud-dashing" width="100%" height="1000" style="border: 0 solid #000000;"></iframe>
  <footer class="footer visible-md visible-lg">
    <div class="container">
      <div class="text-muted">
        copyright@公有云监控
      </div>
    </div>
  </footer>
{% endblock %}

PuZheng/cloud-dashing/cloud_dashing/templates/layout.html
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>
      {% block page_title %}
      公有云监控
      {% endblock %}
    </title>
    {% block head_block %}
      <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='components/bootstrap/dist/css/bootstrap.min.css') }}" />
      <link rel="stylesheet" href="{{ url_for('static', filename='components/fancybox/source/jquery.fancybox.css') }}" />
      <link rel="stylesheet" href="{{ url_for('static', filename='components/normalize-css/normalize.css') }}" />
      <link rel="stylesheet" href="{{ url_for('static', filename='components/select2/select2.css') }}" />
      <link rel="stylesheet" href="{{ url_for('static', filename='components/Font-Awesome/css/font-awesome.min.css') }}" />
      <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}"/>
      <link rel="stylesheet" href="{{ url_for('static', filename='components/toastr/toastr.min.css') }}"/>
      <!--[if lt IE 9]>
          <script src="{{ url_for('static', filename='components/html5shiv/dist/html5shiv.js') }}"></script>
      <![endif]-->
      <script type="text/javascript" src="{{ url_for('static', filename='components/modernizr/modernizr.js') }}"></script>
    {% endblock %}
  </head>
<body>
  {% block nav_bar_block %}
  <!--put nav bar here-->
  {% endblock %}
  {% block main %}
  <!--put your main block here -->
  {% endblock %}
  {% block tail_block %}
    <!--<script type="text/javascript" src="{{ url_for('static', filename='components/bootstrap/dist/js/bootstrap.min.js') }}"></script>-->
    <!--<script type="text/javascript" src="{{ url_for('static', filename='components/fancybox/source/jquery.fancybox.pack.js') }}"></script>-->
    <script type="text/javascript" src="{{ url_for('static', filename='components/holderjs/holder.js') }}"></script>
    <!--<script type="text/javascript" src="{{ url_for('static', filename='components/select2/select2.min.js') }}"></script>-->
    <script type="text/javascript" src="{{ url_for('static', filename='components/handlebars/handlebars.min.js') }}"></script>
  {% endblock %}
</body>
</html>

PuZheng/cloud-dashing/cloud_dashing/templates/user/list.html
{% extends "data_browser__/list.html" %}

{% block body %}
<div class="row">
  {{ sub_nav_bar.as_ul(highlight_class='active')|safe }}
</div>
<div class="row">
    {% block lists %} 
      {{ super() }}
    {% endblock %}
    <div class="col-lg-2">
      {% block filters %}
        {{ super() }}
      {% endblock filters %}
    </div>
</div>
{% endblock %}

PuZheng/cloud-dashing/cloud_dashing/templates/user/login.html
{% extends "layout.html" %}

{% block page_title %}
  公有云监控 - login
{% endblock %}

{% block main %}
  <div class="container">

    <form action="{{ url_for("user.login") }}" role="form" class="alert alert-info form-horizontal form-signin" method="POST">

      <div>
        <h4>{{ _("please login: ") }}</h4>
      </div>
      <hr/>
      {% if error %}
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ error }}
        </div>
      {% endif %}
      {{ form.csrf_token }}

      <div class="form-group">
        <label class="sr-only">{{ _("login") }}</label>
        <div class="input-group col-lg-12">
          <span class="input-group-addon">
            <i class="fa fa-user fa-fw"></i>
          </span>
          <input type="text" name="username" id="username" required="required" placeholder="{{ _('username') }}" class="form-control"/>
        </div>

      </div>
      <div class="form-group">
        <label class="sr-only">{{ _('password') }}</label>
        <div class="input-group col-lg-12">
          <span class="input-group-addon">
            <i class="fa fa-fw fa-keyboard-o"></i>
          </span>
          <input type="password" name="password" id="password" required="required" placeholder="{{ _('password') }}" class="form-control"/>
        </div>
      </div>
      <hr>
      <div class="form-group">
        <div class="col-lg-12">
          <button class="btn btn-block btn-lg btn-success">
            <i class="fa fa-sign-in fa-fw fa-lg"></i>{{ _('login') }}
          </button>
        </div>
      </div>
      {% if next_url %}
        <input type="hidden" name="next_url" value="{{ next_url }}">
      {% endif %}
    </form>
  </div>
{% endblock %}

PuZheng/cloud-dashing/cloud_dashing/templates/user/nav-bar.html
<ul class="nav nav-tabs">
    {% for nav_link in nav_links %}
      {% if nav_link.enabler() %}
        <li class="{{ highlight_class }}">
          <a href="{{ nav_link.url }}">
            <strong>{{ nav_link.anchor }}</strong>
          </a>
        </li>
      {% else %}
        <li class="{{ normal_class }}">
          <a href="{{ nav_link.url }}">{{ nav_link.anchor }}</a>
        </li>
      {% endif %}
    {% endfor %}
</ul>